-- Ingredients
INSERT INTO ingredients (name)
VALUES
	('mozzarella'),
	('shredded mozzarella'),	
	('cream cheese'),
	('almond flour'),
	('blanched almond flour'),
	('salt'),
	('kosher salt'),
	('hot dogs'),
	('egg'),
	('oregano'),
	('psyllium rusk'),
	('yeast'),
	('yeast for bread'),
	('baking powder'),
	('olive oil'),
	('broccoli'),
	('chopped broccoli'),
	('cheddar'),
	('cheddar (in cubes)'),
	('almonds'),
	('thinly sliced almonds'),
	('red onion'),
	('diced red onion'),
	('bacon'),
	('bacon (fried and crambled)'),
	('mayonnaise'),
	('sour cream'),
	('onion powder'),
	('garlic powder'),
	('wine vinegar'),
	('white vinegar'),
	('large egg'),
	('dried parsley'),
	('Pink Himalayan salt'),
	('Sriracha Hot chili sauce'),
	('chicken breast'),
	('shredded chicken breast'),
	('chicken breast (in cubes)'),
	('cod fish'),
	('onion'),
	('green pepper'),
	('yellow pepper'),
	('red pepper'),
	('black olive'),
	('heavy cream'),
	('yellow mustard'),
	('mustard'),
	('paprika'),
	('black pepper'),
	('parsley'),
	('coconut oil'),
	('peanut butter'),
	('cocoa powder'),
	('sweetner'),
	('vanilla extract'),
	('unsalted butter'),
	('butter'),
	('Beef Stew'),
	('grape tomatoes'),
	('soy sauce'),
	('garlic'),
	('minced garlic'),
	('parmesan cheese'),
	('ground beef'),
	('zucchini'),
	('ricotta cheese'),
	('marinara sauce'),
	('coarse sea salt');
