-- Ingredients
INSERT INTO ingredients (name)
VALUES
	('mozzarella'),
	('cream cheese'),
	('almond flour'),
	('salt'),
	('egg'),
	('oregano'),
	('psyllium rusk'),
	('yeast'),
	('yeast for bread'),
	('baking powder'),
	('olive oil'),
	('broccoli'),
	('chopped broccoli'),
	('cheddar'),
	('cheddar (in cubes)'),
	('almonds'),
	('thinly sliced almonds'),
	('red onion'),
	('diced red onion'),
	('bacon'),
	('bacon (fried and crambled)'),
	('mayonnaise'),
	('sour cream'),
	('onion powder'),
	('garlic powder'),
	('wine vinegar'),
	('white vinegar'),
	('large egg'),
	('dried parsley'),
	('Pink Himalayan salt'),
	('Sriracha Hot  chili sauce'),
	('chicken breast'),
	('cod fish'),
	('onion'),
	('green pepper'),
	('yellow pepper'),
	('red pepper'),
	('black olive'),
	('heavy cream'),
	('yellow mustard'),
	('paprika'),
	('black pepper'),
	('parsley'),
	('coconut oil'),
	('peanut butter'),
	('cocoa powder'),
	('sweetner'),
	('vanila extract'),
	('unsalted butter'),
	('butter'),
	('Beef Stew'),
	('grape tomatoes'),
	('soy sauce'),
	('garlic'),
	('parmesan cheese'),
	('coarse sea salt');
